apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: residences.ehu.gcis.org
spec:
  group: ehu.gcis.org
  names:
    kind: Residence
    plural: residences
    singular: residence
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Readiness of the created resource
      jsonPath: .status.ready
      name: Ready
      priority: 0
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      priority: 0
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              deploy:
                type: boolean
              name:
                type: string
              rooms:
                items:
                  properties:
                    deploy:
                      type: boolean
                    name:
                      type: string
                    patients:
                      items:
                        properties:
                          applications:
                            items:
                              properties:
                                components:
                                  items:
                                    properties:
                                      customization:
                                        items:
                                          type: string
                                        type: array
                                      events:
                                        items:
                                          properties:
                                            actions:
                                              items:
                                                properties:
                                                  customization:
                                                    items:
                                                      type: string
                                                    type: array
                                                  image:
                                                    type: string
                                                  name:
                                                    type: string
                                                type: object
                                              type: array
                                            name:
                                              type: string
                                          type: object
                                        required:
                                        - name
                                        - actions
                                        type: array
                                      flowConfig:
                                        properties:
                                          next:
                                            items:
                                              properties:
                                                IFMHtopic:
                                                  type: string
                                                name:
                                                  type: string
                                              type: object
                                            type: array
                                          previous:
                                            items:
                                              properties:
                                                IFMHtopic:
                                                  type: string
                                                name:
                                                  type: string
                                              type: object
                                            type: array
                                        type: object
                                      image:
                                        type: string
                                      name:
                                        type: string
                                      permanent:
                                        type: boolean
                                    required:
                                    - name
                                    - image
                                    - flowConfig
                                    type: object
                                  type: array
                                deploy:
                                  type: boolean
                                name:
                                  type: string
                                replicas:
                                  maximum: 10
                                  minimum: 1
                                  type: integer
                              required:
                              - components
                              - replicas
                              - deploy
                              type: object
                            type: array
                          deploy:
                            type: boolean
                          name:
                            type: string
                        type: object
                      type: array
                  type: object
                type: array
            type: object
          status:
            properties:
              ready:
                type: string
              rooms:
                items:
                  properties:
                    name:
                      type: string
                    status:
                      type: string
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      scale:
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.replicas
      status: {}
