apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-triggerer
  labels:
    ehu.gcis: dummy-event-triggerer
spec:
  replicas: 1
  selector:
    matchLabels:
      ehu.gcis: dummy-event-triggerer
  template:
    metadata:
      labels:
        ehu.gcis: dummy-event-triggerer
    spec:
      containers:
      - image: julencuadra/gcis-fog:event-triggerer
        imagePullPolicy: Always
        name: event-triggerer
        resources: {}
      restartPolicy: Always
      serviceAccountName: service-account-event-triggerer
      nodeSelector:
        node-role.kubernetes.io/master: "true"    # Para desplegarlo en el master
status: {}