apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: patient-controller
  name: patient-controller-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-controller
  template:
    metadata:
      labels:
        app: patient-controller
    spec:
      containers:
      - env:
        - name: LEVEL_NAME
          value: patient
        - name: LEVEL_NAME_PLURAL
          value: patients
        - name: LOWER_LEVEL_NAME
          value: application
        - name: LOWER_LEVEL_NAME_PLURAL
          value: applications
        - name: HIGHER_LEVEL_NAME
          value: room
        - name: HIGHER_LEVEL_NAME_PLURAL
          value: rooms
        image: julencuadra/gcis-fog:generic-app-management-level-controller
        imagePullPolicy: Always
        name: patient-controller
        ports:
        - containerPort: 80
      nodeSelector:
        node-role.kubernetes.io/master: 'true'
      serviceAccountName: service-account-controller-patient
