apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: residence-controller
  name: residence-controller-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: residence-controller
  template:
    metadata:
      labels:
        app: residence-controller
    spec:
      containers:
      - env:
        - name: LEVEL_NAME
          value: residence
        - name: LEVEL_NAME_PLURAL
          value: residences
        - name: LOWER_LEVEL_NAME
          value: room
        - name: LOWER_LEVEL_NAME_PLURAL
          value: rooms
        - name: HIGHER_LEVEL_NAME
          value: system
        - name: HIGHER_LEVEL_NAME_PLURAL
          value: systems
        image: julencuadra/gcis-fog:generic-app-management-level-controller
        imagePullPolicy: Always
        name: residence-controller
        ports:
        - containerPort: 80
      nodeSelector:
        node-role.kubernetes.io/master: 'true'
      serviceAccountName: service-account-controller-residence
