apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-event-manager
rules:
- apiGroups:
  - ehu.gcis.org
  resources:
  - components
  verbs:
  - get
  - list
  - watch
  - patch
  - create
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - patch
  - create
  - delete
- apiGroups:
  - ''
  resources:
  - events
  - configmaps
  verbs:
  - get
  - list
  - watch
  - patch
  - create
  - delete
