apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-controller-room
rules:
- apiGroups:
  - ehu.gcis.org
  resources:
  - rooms
  - rooms/status
  verbs:
  - get
  - list
  - watch
  - patch
  - create
  - delete
- apiGroups:
  - ehu.gcis.org
  resources:
  - patients
  - patients/status
  verbs:
  - list
  - get
  - put
  - patch
  - create
  - update
  - delete
- apiGroups:
  - ehu.gcis.org
  resources:
  - residences
  - residences/status
  verbs:
  - get
  - patch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - post
  - put
  - patch
  - create
  - update
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - watch
  - create
  - patch
  - update
  - get
